/* Feng runtime — public ABI consumed by codegen-emitted C code.
 *
 * All symbols listed in this header constitute the Phase 1A runtime contract.
 * Anything not declared here MUST NOT be referenced by generated code; future
 * phases will extend this surface deliberately.
 */
#ifndef FENG_RUNTIME_H
#define FENG_RUNTIME_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if !defined(_WIN32)
#include <unwind.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* --- Type descriptors -------------------------------------------------- */

typedef enum FengTypeTag {
    FENG_TYPE_TAG_STRING = 1,
    FENG_TYPE_TAG_ARRAY = 2,
    FENG_TYPE_TAG_OBJECT = 3,
    FENG_TYPE_TAG_CLOSURE = 4
} FengTypeTag;

typedef void (*FengFinalizerFn)(void *self);

/* Codegen-emitted "release children" callback. Invoked by the ARC release
 * path immediately before `free()` to drop every managed reference held by
 * the dying object's fields. This slot is conceptually distinct from
 * `finalizer` — see docs/feng-lifetime.md §11/§13.2:
 *
 *   - `finalizer` is OPTIONAL and reflects user-declared semantics only.
 *     The cycle collector invokes it under the §13.2 two-phase rule and
 *     re-checks refcount afterwards (resurrection support).
 *   - `release_children` is unconditionally generated by codegen for every
 *     type that holds at least one managed field. The cycle collector NEVER
 *     calls it on objects in a reclaimed cycle (the collector frees the
 *     whole component as a unit, so per-field releases would dec refcounts
 *     of objects that are about to be freed alongside).
 *
 * Built-in tags (string/array) leave this slot NULL and rely on the
 * tag-specific runtime hook (`feng_string_finalize_internal` etc.). */
typedef void (*FengReleaseChildrenFn)(void *self);
typedef bool (*FengValueEqualFn)(const void *left, const void *right);

/* Static description of a single managed reference slot inside an object.
 * `offset` is the byte offset of the slot relative to the object base
 * (i.e. relative to its FengManagedHeader). `static_desc` is the descriptor
 * the slot was declared to hold; it MAY be NULL when the slot is polymorphic
 * (e.g. a closure capture of a managed value whose precise type the codegen
 * cannot pin down at emission time). The cycle collector treats `static_desc`
 * as a hint only — the actual descriptor of the pointed-to object is always
 * read from its own header.
 *
 * This metadata is consumed exclusively by the runtime cycle collector
 * (Phase 1B). The deterministic ARC release path does not consult it; the
 * codegen-emitted user finalizer remains the sole owner of the per-field
 * release sequence so the ARC fast path stays Phase 1A compatible. */
typedef struct FengManagedFieldDescriptor {
    size_t offset;
    const struct FengTypeDescriptor *static_desc;
} FengManagedFieldDescriptor;

typedef struct FengTypeDescriptor {
    const char *name;            /* fully-qualified, debug-only */
    size_t size;                 /* total instance bytes incl. header (0 for variable-length) */
    FengFinalizerFn finalizer;   /* optional user-defined finalizer (semantic) */
    FengReleaseChildrenFn release_children; /* codegen-emitted; see typedef */

    /* --- Phase 1B reference-graph metadata ----------------------------- */

    /* True iff the static type-reference graph places this type in a
     * non-trivial strongly-connected component (i.e. self-loop or part of a
     * cycle). The cycle collector only ever enqueues objects whose descriptor
     * has this flag set; acyclic objects bypass the candidate buffer entirely
     * and follow the deterministic ARC release path with zero collector
     * overhead. */
    bool is_potentially_cyclic;

    /* Static trace table: enumeration of every managed reference slot
     * directly held by an instance of this type. Fixed-layout types (user
     * `type`, closures with concrete capture lists) populate it; variable-
     * layout built-ins (string/array) leave it empty and expose their
     * managed children through a tag-specific runtime hook instead. */
    size_t managed_field_count;
    const FengManagedFieldDescriptor *managed_fields;
    FengValueEqualFn equal_fn;   /* NULL => managed pointer identity */
} FengTypeDescriptor;

typedef struct FengTrivialDescriptor {
    const char *name;            /* fully-qualified or builtin, debug-only */
    size_t size;                 /* sizeof(T) for the trivial value */
    FengValueEqualFn equal_fn;   /* NULL => memcmp(left, right, size) == 0 */
} FengTrivialDescriptor;

/* Built-in descriptors used by string/array helpers. Generated code may also
 * reference them when emitting array-of-string or array-of-array slots. */
extern const FengTypeDescriptor feng_string_descriptor;
extern const FengTypeDescriptor feng_array_descriptor;

extern const FengTrivialDescriptor feng_bool_descriptor;
extern const FengTrivialDescriptor feng_i8_descriptor;
extern const FengTrivialDescriptor feng_i16_descriptor;
extern const FengTrivialDescriptor feng_i32_descriptor;
extern const FengTrivialDescriptor feng_i64_descriptor;
extern const FengTrivialDescriptor feng_u8_descriptor;
extern const FengTrivialDescriptor feng_u16_descriptor;
extern const FengTrivialDescriptor feng_u32_descriptor;
extern const FengTrivialDescriptor feng_u64_descriptor;
extern const FengTrivialDescriptor feng_f32_descriptor;
extern const FengTrivialDescriptor feng_f64_descriptor;
extern const FengTrivialDescriptor feng_pointer_descriptor;

/* --- Managed object header --------------------------------------------- */

typedef struct FengManagedHeader {
    const FengTypeDescriptor *desc;
    FengTypeTag tag;
    /* refcount == UINT32_MAX marks the object as immortal (string literals,
     * runtime-internal singletons). retain/release skip such objects. */
    uint32_t refcount;
    /* Phase 1B cycle collector workspace. The field is read-only outside the
     * collector; acyclic objects (descriptor->is_potentially_cyclic == false)
     * never have it mutated from the zero-initialised state, so the ARC fast
     * path remains free of collector overhead.
     *
     * Encoded layout:
     *   bits 0..1 — Bacon-Rajan colour:
     *               0 = BLACK   (in use; default after calloc)
     *               1 = GREY    (currently being traced)
     *               2 = WHITE   (provisionally part of an unreachable cycle)
     *               3 = PURPLE  (reserved for future incremental collector)
     *   bit  2    — buffered: object is currently sitting in the candidate
     *               buffer waiting for a collection cycle.
     *   bit  3    — collecting: object is in the white-set the collector is
     *               currently freeing; feng_release must not run the ARC
     *               finalize path for it (the collector owns its destruction
     *               in Phase 2). */
    uint32_t cycle_state;
} FengManagedHeader;

/* Runtime-internal stable subject owner for escaping scalar spec values.
 * Codegen reads payload directly in witness thunks and invokes the typed
 * constructors below at coercion sites. */
typedef enum FengBuiltinScalarKind {
    FENG_BUILTIN_SCALAR_BOOL = 1,
    FENG_BUILTIN_SCALAR_I8 = 2,
    FENG_BUILTIN_SCALAR_I16 = 3,
    FENG_BUILTIN_SCALAR_I32 = 4,
    FENG_BUILTIN_SCALAR_I64 = 5,
    FENG_BUILTIN_SCALAR_U8 = 6,
    FENG_BUILTIN_SCALAR_U16 = 7,
    FENG_BUILTIN_SCALAR_U32 = 8,
    FENG_BUILTIN_SCALAR_U64 = 9,
    FENG_BUILTIN_SCALAR_F32 = 10,
    FENG_BUILTIN_SCALAR_F64 = 11
} FengBuiltinScalarKind;

typedef struct FengScalarBox {
    FengManagedHeader header;
    FengBuiltinScalarKind kind;
    union {
        bool b;
        int8_t i8;
        int16_t i16;
        int32_t i32;
        int64_t i64;
        uint8_t u8;
        uint16_t u16;
        uint32_t u32;
        uint64_t u64;
        float f32;
        double f64;
    } payload;
} FengScalarBox;

extern const FengTypeDescriptor feng_scalar_box_descriptor;
extern const FengTypeDescriptor feng_scalar_bool_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_i8_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_i16_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_i32_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_i64_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_u8_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_u16_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_u32_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_u64_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_f32_exception_descriptor;
extern const FengTypeDescriptor feng_scalar_f64_exception_descriptor;

FengScalarBox *feng_scalar_box_new_bool(bool value);
FengScalarBox *feng_scalar_box_new_i8(int8_t value);
FengScalarBox *feng_scalar_box_new_i16(int16_t value);
FengScalarBox *feng_scalar_box_new_i32(int32_t value);
FengScalarBox *feng_scalar_box_new_i64(int64_t value);
FengScalarBox *feng_scalar_box_new_u8(uint8_t value);
FengScalarBox *feng_scalar_box_new_u16(uint16_t value);
FengScalarBox *feng_scalar_box_new_u32(uint32_t value);
FengScalarBox *feng_scalar_box_new_u64(uint64_t value);
FengScalarBox *feng_scalar_box_new_f32(float value);
FengScalarBox *feng_scalar_box_new_f64(double value);

#define FENG_REFCOUNT_IMMORTAL ((uint32_t)0xFFFFFFFFu)

/* --- retain / release / barriers --------------------------------------- */

void *feng_retain(void *obj);
void  feng_release(void *obj);

/* Slot assignment with RC barrier:
 *   release(*slot); *slot = retain(new_value); */
void  feng_assign(void **slot, void *new_value);

/* Take ownership of a slot, leaving it NULL. Refcount is unchanged: the caller
 * inherits the +1 reference. */
void *feng_take(void **slot);

/* --- Value model: by-value aggregates with managed slots --------------- */
/*
 * The runtime classifies every Feng value into one of three categories
 * (see dev/feng-value-model-delivered.md §2):
 *
 *   FENG_VALUE_TRIVIAL          — bytes only, no retain/release; codegen
 *                                 emits direct C assignment / memcpy.
 *   FENG_VALUE_MANAGED_POINTER  — single managed pointer, handled by the
 *                                 existing single-pointer primitives.
 *   FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS — by-value composite holding
 *                                 at least one managed slot; lifecycle is
 *                                 driven by FengAggregateDescriptor
 *                                 below.
 *
 * `FengValueKind` is consumed by codegen for site dispatch and by the
 * runtime array layer for per-element dispatch (see feng_array_new_kinded);
 * the single-pointer primitives themselves never branch on it. */
typedef enum FengValueKind {
    FENG_VALUE_TRIVIAL = 1,
    FENG_VALUE_MANAGED_POINTER = 2,
    FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS = 3
} FengValueKind;

/* ---- Generic parameter descriptor (G6 — layout monomorphization + method sharing) ----
 * Passed as one hidden argument per type parameter to generic shared bodies.
 * Carries the minimum runtime information needed by erased code to correctly
 * copy, retain, release, and later dispatch through witness slots for values
 * of the erased type parameter.
 *
 *   kind       — ARC classification; drives the switch in generic return/copy.
 *   descriptor — concrete descriptor for the current kind. Cast target is
 *                FengTrivialDescriptor, FengTypeDescriptor, or
 *                FengAggregateDescriptor according to `kind`.
 *   witness    — optional static witness instance for the current generic
 *                constraint surface; NULL when the type parameter is
 *                unconstrained. */
typedef struct FengGenericParamDescriptor {
    FengValueKind   kind;
    const void     *descriptor;
    const void     *witness;
} FengGenericParamDescriptor;

/* Single managed slot inside a by-value aggregate. `offset` is measured from
 * the aggregate value's base address (NOT from a FengManagedHeader). */
typedef enum FengManagedSlotKind {
    /* Slot itself is one managed pointer. The aggregate APIs use
     * feng_retain/feng_release/feng_assign on `*(void**)(value + offset)`. */
    FENG_SLOT_POINTER = 1,
    /* Slot embeds another by-value aggregate; walker recurses through
     * `nested`. */
    FENG_SLOT_NESTED_AGGREGATE = 2
} FengManagedSlotKind;

typedef struct FengManagedSlotDescriptor {
    size_t offset;
    FengManagedSlotKind kind;
    /* Required iff kind == FENG_SLOT_NESTED_AGGREGATE; otherwise must be
     * NULL. */
    const struct FengAggregateDescriptor *nested;
} FengManagedSlotDescriptor;

/* Default-initialisation strategy for an aggregate value. Some aggregates
 * (e.g. fat object-form spec) cannot tolerate all-zero bytes as their
 * default state because their managed slots must point at retained, valid
 * objects from the very first observation. */
typedef enum FengAggregateDefaultKind {
    /* All-zero bytes (NULL pointers in every managed slot) is a legal
     * default. feng_aggregate_default_init resolves to memset(0). */
    FENG_DEFAULT_ZERO_BYTES = 1,
    /* Type provides a custom initialiser that produces a fully-constructed
     * value with all managed slots properly retained. */
    FENG_DEFAULT_INIT_FN = 2
} FengAggregateDefaultKind;

/* Init function contract: on entry `value_out` points to `desc->size` bytes
 * of indeterminate content; on return, every managed slot must hold either
 * NULL or a +1 retained reference, and any non-managed bytes must hold a
 * legal value. The function MUST NOT throw a Feng exception. */
typedef void (*FengAggregateDefaultInitFn)(void *value_out);

typedef struct FengAggregateDefaultInitDescriptor {
    FengAggregateDefaultKind kind;
    /* Only consulted when kind == FENG_DEFAULT_INIT_FN. */
    FengAggregateDefaultInitFn init_fn;
} FengAggregateDefaultInitDescriptor;

typedef struct FengAggregateDescriptor {
    /* Fully-qualified, debug-only. May be NULL. */
    const char *name;
    /* Total bytes the aggregate occupies. */
    size_t size;
    /* Default-initialisation policy. MUST be non-NULL; the runtime panics
     * on default-init of a NULL policy. */
    const FengAggregateDefaultInitDescriptor *default_init;
    /* Managed slot table in declaration order. Slots that are non-managed
     * (trivial bytes) are NOT enumerated. */
    size_t managed_slot_count;
    const FengManagedSlotDescriptor *managed_slots;
    FengValueEqualFn equal_fn;   /* NULL => no aggregate equality support */
} FengAggregateDescriptor;

static inline const FengTrivialDescriptor *feng_generic_trivial_descriptor(
        const FengGenericParamDescriptor *param) {
    return (const FengTrivialDescriptor *)param->descriptor;
}

static inline const FengTypeDescriptor *feng_generic_type_descriptor(
        const FengGenericParamDescriptor *param) {
    return (const FengTypeDescriptor *)param->descriptor;
}

static inline const FengAggregateDescriptor *feng_generic_aggregate_descriptor(
        const FengGenericParamDescriptor *param) {
    return (const FengAggregateDescriptor *)param->descriptor;
}

static inline size_t feng_generic_value_size(const FengGenericParamDescriptor *param) {
    switch (param->kind) {
        case FENG_VALUE_TRIVIAL:
            return feng_generic_trivial_descriptor(param)->size;
        case FENG_VALUE_MANAGED_POINTER:
            return sizeof(void *);
        case FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS:
            return feng_generic_aggregate_descriptor(param)->size;
    }
    return 0U;
}

/* Five canonical operations over by-value aggregates. All are NULL-safe
 * with respect to managed slot pointers (NULL pointers are skipped); they
 * panic on a NULL `desc` or NULL `value`/`dst`/`src` (programmer error). */

/* Retain every managed pointer reachable from `value` according to `desc`. */
void feng_aggregate_retain(void *value,
                           const FengAggregateDescriptor *desc);

/* Release every managed pointer reachable from `value` according to `desc`.
 * After return, the managed slot bytes are unchanged but the references
 * they once held have been dropped; the caller MUST NOT observe those
 * pointers again (typically the value's storage is about to be overwritten
 * or its stack frame popped). */
void feng_aggregate_release(void *value,
                            const FengAggregateDescriptor *desc);

/* Assignment: semantically equivalent to `*dst = *src` while keeping the
 * refcount invariants of every managed slot.
 *
 * Self-assignment (`dst == src`) is a no-op. The implementation retains
 * every source slot first, releases every destination slot next, then
 * memcpys the whole aggregate; this gives correct results when source and
 * destination share managed children. */
void feng_aggregate_assign(void *dst, const void *src,
                           const FengAggregateDescriptor *desc);

/* Move: transfers ownership of every managed slot from `src` to `dst`.
 * After return, every managed slot in `src` is set to NULL; non-managed
 * bytes in `src` are left as-is. The destination's previous managed slots
 * are released as in feng_aggregate_release.
 *
 * Self-move (`dst == src`) is a no-op. */
void feng_aggregate_take(void *dst, void *src,
                         const FengAggregateDescriptor *desc);

/* Initialise `value_out` to the descriptor's default value. */
void feng_aggregate_default_init(void *value_out,
                                 const FengAggregateDescriptor *desc);

/* --- String ------------------------------------------------------------ */

typedef struct FengString FengString;

/* Allocates a fresh immortal string holding a copy of the supplied UTF-8 bytes.
 * Codegen caches the returned pointer per literal site so each literal allocates
 * exactly once at first use. The buffer is null-terminated. */
FengString *feng_string_literal(const char *utf8, size_t length);

/* Process-wide singleton empty string used as the `string` default zero value.
 * Stamped IMMORTAL so retain/release are no-ops; safe to share across threads.
 * Generated code uses this at every binding/field site that has no explicit
 * initialiser so `string` defaults to a real empty string rather than NULL. */
FengString *feng_string_default(void);

/* Concatenation always returns a fresh +1 string; either operand may be NULL,
 * which is treated as the empty string. */
FengString *feng_string_concat(const FengString *left, const FengString *right);

size_t      feng_string_length(const FengString *s);
const char *feng_string_data(const FengString *s);

/* --- Array ------------------------------------------------------------- */

typedef struct FengArray FengArray;

/* Creates a fresh +1 array. Element classification follows
 * dev/feng-value-model-delivered.md §7.3:
 *
 *   FENG_VALUE_TRIVIAL          — `element_aggregate` MUST be NULL; slots
 *                                 hold raw bytes and finalize merely frees
 *                                 the storage.
 *   FENG_VALUE_MANAGED_POINTER  — `element_aggregate` MUST be NULL;
 *                                 element_size MUST equal sizeof(void *);
 *                                 each non-NULL slot is feng_release'd on
 *                                 finalize.
 *   FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS — `element_aggregate` MUST be
 *                                 non-NULL and `element_size` MUST equal
 *                                 `element_aggregate->size`; each element is
 *                                 released via feng_aggregate_release on
 *                                 finalize.
 *
 * `element_desc` is currently used only for diagnostics; pass NULL when the
 * caller has nothing meaningful (e.g. aggregate elements). All
 * preconditions are enforced with feng_panic to surface descriptor /
 * codegen mistakes early. */
FengArray *feng_array_new_kinded(FengValueKind element_kind,
                                 const FengAggregateDescriptor *element_aggregate,
                                 const FengTypeDescriptor *element_desc,
                                 size_t element_size,
                                 size_t length);

/* Legacy two-way constructor preserved verbatim for callers that have not
 * yet adopted the kinded API. Wraps feng_array_new_kinded with
 * `element_aggregate = NULL` and dispatches `element_is_managed` to
 * MANAGED_POINTER vs TRIVIAL. New code MUST use feng_array_new_kinded for
 * aggregate-element arrays. */
FengArray *feng_array_new(const FengTypeDescriptor *element_desc,
                          size_t element_size,
                          bool element_is_managed,
                          size_t length);

size_t feng_array_length(const FengArray *array);
void  *feng_array_data(FengArray *array);
void   feng_array_check_index(const FengArray *array, size_t index);

/* Reports the per-element classification recorded at array creation. The
 * runtime itself does not branch on this value (the finalize path uses
 * the cached classification directly); callers that walk arrays from
 * generated code may consult it to pick the correct copy/assign path. */
FengValueKind feng_array_element_kind(const FengArray *array);

/* Returns the per-element aggregate descriptor for AGGREGATE-kind arrays,
 * or NULL otherwise. */
const FengAggregateDescriptor *feng_array_element_aggregate(const FengArray *array);

/* Runtime-contract note: `feng_array_slice(array, start, length)` copies the
 * right-open range [start, start + length) into a fresh +1 FengArray. The returned
 * array reuses the source array's per-element metadata (kind / descriptor /
 * aggregate descriptor) but owns an independent payload allocation. When
 * the sliced range contains managed children, the helper acquires the
 * returned array's own holds before returning. The declaration itself lives
 * in feng_runtime_contract.inc with the rest of the `@runtime` allow-list. */

/* --- Object ------------------------------------------------------------ */

/* Allocates a zero-initialised instance whose first member is FengManagedHeader.
 * desc->size MUST cover the full struct including the header. */
void *feng_object_new(const FengTypeDescriptor *desc);

/* --- Exceptions -------------------------------------------------------- */

/* Feng exception class written into the platform unwind header. The byte
 * sequence is "FENGEXN\0" and lets the personality function distinguish Feng
 * exceptions from foreign-language unwind payloads. */
#define FENG_EXCEPTION_CLASS UINT64_C(0x46454E4745584E00)

/* One catch clause in a generated LSDA table. A NULL type is the `unknown`
 * catch-all clause; otherwise matching is descriptor-pointer identity. */
typedef struct FengCatchClause {
    const FengTypeDescriptor *type;
} FengCatchClause;

/* Static language-specific data generated per try region. `pc_begin`,
 * `pc_end`, and `landing_pad` are generated label addresses. */
typedef struct FengLSDA {
    const void *pc_begin;
    const void *pc_end;
    const void *landing_pad;
    const FengCatchClause *clauses;
    int clause_count;
} FengLSDA;

void feng_register_lsda(const FengLSDA *regions, int region_count);

#if !defined(_WIN32)
extern const FengLSDA feng_empty_function_lsda[1];
_Unwind_Reason_Code __feng_personality_v0(int version,
                                          _Unwind_Action actions,
                                          uint64_t exception_class,
                                          struct _Unwind_Exception *unwind,
                                          struct _Unwind_Context *context);
#endif

/* Heap-owned in-flight exception object. On Unix-like platforms the platform
 * unwind header must be the first field so libunwind can treat this object as
 * a native `_Unwind_Exception`. Windows uses the same Feng payload surface and
 * stores the SEH payload in the platform layer. */
typedef struct FengUnwindException {
#if defined(_WIN32)
    uint64_t exception_class;
#else
    struct _Unwind_Exception unwind;
#endif
    void *value;
    const FengTypeDescriptor *desc;
    int matched_clause;
} FengUnwindException;

/* Linked-list node living on the C stack. Generated code pushes one of these
 * at every managed local's declaration site (binding or materialised
 * temporary) and pops it on the corresponding scope exit. On throw, the
 * runtime walks the chain back to the catching frame's snapshot and releases
 * every non-NULL `*slot`, then nulls the slot to avoid double-free. This is
 * how Phase 1A guarantees "exception path cleanup" without hoisting locals
 * to the function prologue. */
typedef struct FengCleanupNode {
    struct FengCleanupNode *prev;
    void                  **slot;
} FengCleanupNode;

/* Function-frame boundary marker inserted into the cleanup chain. It carries
 * no managed slot; unwind cleanup stops at this marker after releasing the
 * current frame's managed locals. */
typedef struct FengFrameMarker {
    FengCleanupNode node;
    bool            is_function_boundary;
} FengFrameMarker;

/* Push/pop a managed local onto the cleanup chain. `node` must outlive the
 * scope of `slot` and is typically a stack-allocated FengCleanupNode adjacent
 * to the local. Pop must be called in strict LIFO order. */
void feng_cleanup_push(FengCleanupNode *node, void **slot);
void feng_cleanup_pop(void);
void feng_frame_push(FengFrameMarker *marker);
void feng_try_frame_push(FengFrameMarker *marker);
void feng_frame_pop(void);
void feng_frame_release_to(FengFrameMarker *marker);

void *feng_caught_value(void);
int   feng_caught_clause(void);
void  feng_release_unwind_exception(void);

#if defined(__GNUC__) || defined(__clang__)
void feng_throw(void *value, const FengTypeDescriptor *desc) __attribute__((noreturn));
void feng_rethrow(void) __attribute__((noreturn));
#else
void feng_throw(void *value, const FengTypeDescriptor *desc);
void feng_rethrow(void);
#endif

/* --- Panic ------------------------------------------------------------- */

#if defined(__GNUC__) || defined(__clang__)
void feng_panic(const char *fmt, ...) __attribute__((noreturn, format(printf, 1, 2)));
#else
void feng_panic(const char *fmt, ...);
#endif

/* --- Runtime Contract ------------------------------------------------- */

/* Runtime-contract declarations shared by generated `@runtime` calls and the
 * runtime implementation. Keep this fragment as the single source of truth
 * for which runtime symbols codegen may accept on the `@runtime` path. */
#define FENG_RUNTIME_CONTRACT(ret_type, name, args) ret_type name args;
#include "runtime/feng_runtime_contract.inc"
#undef FENG_RUNTIME_CONTRACT

/* --- Lifecycle --------------------------------------------------------- */

/* Drains any potentially-cyclic objects still sitting in the cycle
 * collector's candidate buffer and releases collector-owned heap. Codegen
 * emits a call to this from main() immediately before returning, so user
 * cycles formed but never reclaimed during normal execution still reach
 * their finalizers at process exit. Idempotent and thread-safe. */
void feng_runtime_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif /* FENG_RUNTIME_H */
