/* Feng runtime — public ABI consumed by codegen-emitted C code.
 *
 * All symbols listed in this header constitute the Phase 1A runtime contract.
 * Anything not declared here MUST NOT be referenced by generated code; future
 * phases will extend this surface deliberately.
 */
#ifndef FENG_RUNTIME_H
#define FENG_RUNTIME_H

#include <setjmp.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* --- Type descriptors -------------------------------------------------- */

typedef enum FengTypeTag {
    FENG_TYPE_TAG_STRING = 1,
    FENG_TYPE_TAG_ARRAY = 2,
    FENG_TYPE_TAG_OBJECT = 3,
    FENG_TYPE_TAG_CLOSURE = 4
} FengTypeTag;

typedef void (*FengFinalizerFn)(void *self);

/* Codegen-emitted "release children" callback. Invoked by the ARC release
 * path immediately before `free()` to drop every managed reference held by
 * the dying object's fields. This slot is conceptually distinct from
 * `finalizer` — see docs/feng-lifetime.md §11/§13.2:
 *
 *   - `finalizer` is OPTIONAL and reflects user-declared semantics only.
 *     The cycle collector invokes it under the §13.2 two-phase rule and
 *     re-checks refcount afterwards (resurrection support).
 *   - `release_children` is unconditionally generated by codegen for every
 *     type that holds at least one managed field. The cycle collector NEVER
 *     calls it on objects in a reclaimed cycle (the collector frees the
 *     whole component as a unit, so per-field releases would dec refcounts
 *     of objects that are about to be freed alongside).
 *
 * Built-in tags (string/array) leave this slot NULL and rely on the
 * tag-specific runtime hook (`feng_string_finalize_internal` etc.). */
typedef void (*FengReleaseChildrenFn)(void *self);

/* Static description of a single managed reference slot inside an object.
 * `offset` is the byte offset of the slot relative to the object base
 * (i.e. relative to its FengManagedHeader). `static_desc` is the descriptor
 * the slot was declared to hold; it MAY be NULL when the slot is polymorphic
 * (e.g. a closure capture of a managed value whose precise type the codegen
 * cannot pin down at emission time). The cycle collector treats `static_desc`
 * as a hint only — the actual descriptor of the pointed-to object is always
 * read from its own header.
 *
 * This metadata is consumed exclusively by the runtime cycle collector
 * (Phase 1B). The deterministic ARC release path does not consult it; the
 * codegen-emitted user finalizer remains the sole owner of the per-field
 * release sequence so the ARC fast path stays Phase 1A compatible. */
typedef struct FengManagedFieldEntry {
    size_t offset;
    const struct FengTypeDescriptor *static_desc;
} FengManagedFieldEntry;

typedef struct FengTypeDescriptor {
    const char *name;            /* fully-qualified, debug-only */
    size_t size;                 /* total instance bytes incl. header (0 for variable-length) */
    FengFinalizerFn finalizer;   /* optional user-defined finalizer (semantic) */
    FengReleaseChildrenFn release_children; /* codegen-emitted; see typedef */

    /* --- Phase 1B reference-graph metadata ----------------------------- */

    /* True iff the static type-reference graph places this type in a
     * non-trivial strongly-connected component (i.e. self-loop or part of a
     * cycle). The cycle collector only ever enqueues objects whose descriptor
     * has this flag set; acyclic objects bypass the candidate buffer entirely
     * and follow the deterministic ARC release path with zero collector
     * overhead. */
    bool is_potentially_cyclic;

    /* Static trace table: enumeration of every managed reference slot
     * directly held by an instance of this type. Fixed-layout types (user
     * `type`, closures with concrete capture lists) populate it; variable-
     * layout built-ins (string/array) leave it empty and expose their
     * managed children through a tag-specific runtime hook instead. */
    size_t managed_field_count;
    const FengManagedFieldEntry *managed_fields;
} FengTypeDescriptor;

/* Built-in descriptors used by string/array helpers. Generated code may also
 * reference them when emitting array-of-string or array-of-array slots. */
extern const FengTypeDescriptor feng_string_descriptor;
extern const FengTypeDescriptor feng_array_descriptor;

/* --- Managed object header --------------------------------------------- */

typedef struct FengManagedHeader {
    const FengTypeDescriptor *desc;
    FengTypeTag tag;
    /* refcount == UINT32_MAX marks the object as immortal (string literals,
     * runtime-internal singletons). retain/release skip such objects. */
    uint32_t refcount;
    /* Phase 1B cycle collector workspace. The field is read-only outside the
     * collector; acyclic objects (descriptor->is_potentially_cyclic == false)
     * never have it mutated from the zero-initialised state, so the ARC fast
     * path remains free of collector overhead.
     *
     * Encoded layout:
     *   bits 0..1 — Bacon-Rajan colour:
     *               0 = BLACK   (in use; default after calloc)
     *               1 = GREY    (currently being traced)
     *               2 = WHITE   (provisionally part of an unreachable cycle)
     *               3 = PURPLE  (reserved for future incremental collector)
     *   bit  2    — buffered: object is currently sitting in the candidate
     *               buffer waiting for a collection cycle.
     *   bit  3    — collecting: object is in the white-set the collector is
     *               currently freeing; feng_release must not run the ARC
     *               finalize path for it (the collector owns its destruction
     *               in Phase 2). */
    uint32_t cycle_state;
} FengManagedHeader;

#define FENG_REFCOUNT_IMMORTAL ((uint32_t)0xFFFFFFFFu)

/* --- retain / release / barriers --------------------------------------- */

void *feng_retain(void *obj);
void  feng_release(void *obj);

/* Slot assignment with RC barrier:
 *   release(*slot); *slot = retain(new_value); */
void  feng_assign(void **slot, void *new_value);

/* Take ownership of a slot, leaving it NULL. Refcount is unchanged: the caller
 * inherits the +1 reference. */
void *feng_take(void **slot);

/* --- String ------------------------------------------------------------ */

typedef struct FengString FengString;

/* Allocates a fresh immortal string holding a copy of the supplied UTF-8 bytes.
 * Codegen caches the returned pointer per literal site so each literal allocates
 * exactly once at first use. The buffer is null-terminated. */
FengString *feng_string_literal(const char *utf8, size_t length);

/* Process-wide singleton empty string used as the `string` default zero value.
 * Stamped IMMORTAL so retain/release are no-ops; safe to share across threads.
 * Generated code uses this at every binding/field site that has no explicit
 * initialiser so `string` defaults to a real empty string rather than NULL. */
FengString *feng_string_default(void);

/* Concatenation always returns a fresh +1 string; either operand may be NULL,
 * which is treated as the empty string. */
FengString *feng_string_concat(const FengString *left, const FengString *right);

size_t      feng_string_length(const FengString *s);
const char *feng_string_data(const FengString *s);

/* --- Array ------------------------------------------------------------- */

typedef struct FengArray FengArray;

/* Allocates a zero-initialised array of `length` elements. When
 * `element_is_managed` is true, slots are treated as pointers to managed
 * objects and released on array destruction. `element_desc` is currently used
 * only for diagnostics. */
FengArray *feng_array_new(const FengTypeDescriptor *element_desc,
                          size_t element_size,
                          bool element_is_managed,
                          size_t length);

size_t feng_array_length(const FengArray *array);
void  *feng_array_data(FengArray *array);
void   feng_array_check_index(const FengArray *array, size_t index);

/* --- Object ------------------------------------------------------------ */

/* Allocates a zero-initialised instance whose first member is FengManagedHeader.
 * desc->size MUST cover the full struct including the header. */
void *feng_object_new(const FengTypeDescriptor *desc);

/* --- Exceptions -------------------------------------------------------- */

/* Linked-list node living on the C stack. Generated code pushes one of these
 * at every managed local's declaration site (binding or materialised
 * temporary) and pops it on the corresponding scope exit. On throw, the
 * runtime walks the chain back to the catching frame's snapshot and releases
 * every non-NULL `*slot`, then nulls the slot to avoid double-free. This is
 * how Phase 1A guarantees "exception path cleanup" without hoisting locals
 * to the function prologue. */
typedef struct FengCleanupNode {
    struct FengCleanupNode *prev;
    void                  **slot;
} FengCleanupNode;

typedef struct FengExceptionFrame {
    struct FengExceptionFrame *prev;
    jmp_buf jb;
    void   *value;
    int     is_managed;
    /* Snapshot of the cleanup chain top at the moment this frame was pushed.
     * On throw, the runtime walks down to (but not past) this node. */
    struct FengCleanupNode *cleanup_top;
} FengExceptionFrame;

void feng_exception_push(FengExceptionFrame *frame);
void feng_exception_pop(void);

/* Push/pop a managed local onto the cleanup chain. `node` must outlive the
 * scope of `slot` and is typically a stack-allocated FengCleanupNode adjacent
 * to the local. Pop must be called in strict LIFO order. */
void feng_cleanup_push(FengCleanupNode *node, void **slot);
void feng_cleanup_pop(void);

#if defined(__GNUC__) || defined(__clang__)
void feng_exception_throw(void *value, int is_managed) __attribute__((noreturn));
#else
void feng_exception_throw(void *value, int is_managed);
#endif

FengExceptionFrame *feng_exception_current(void);

/* --- Panic ------------------------------------------------------------- */

#if defined(__GNUC__) || defined(__clang__)
void feng_panic(const char *fmt, ...) __attribute__((noreturn, format(printf, 1, 2)));
#else
void feng_panic(const char *fmt, ...);
#endif

/* --- Lifecycle --------------------------------------------------------- */

/* Drains any potentially-cyclic objects still sitting in the cycle
 * collector's candidate buffer and releases collector-owned heap. Codegen
 * emits a call to this from main() immediately before returning, so user
 * cycles formed but never reclaimed during normal execution still reach
 * their finalizers at process exit. Idempotent and thread-safe. */
void feng_runtime_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif /* FENG_RUNTIME_H */
