/* Feng runtime — public ABI consumed by codegen-emitted C code.
 *
 * All symbols listed in this header constitute the Phase 1A runtime contract.
 * Anything not declared here MUST NOT be referenced by generated code; future
 * phases will extend this surface deliberately.
 */
#ifndef FENG_RUNTIME_H
#define FENG_RUNTIME_H

#include <setjmp.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* --- Type descriptors -------------------------------------------------- */

typedef enum FengTypeTag {
    FENG_TYPE_TAG_STRING = 1,
    FENG_TYPE_TAG_ARRAY = 2,
    FENG_TYPE_TAG_OBJECT = 3,
    FENG_TYPE_TAG_CLOSURE = 4
} FengTypeTag;

typedef void (*FengFinalizerFn)(void *self);

/* Codegen-emitted "release children" callback. Invoked by the ARC release
 * path immediately before `free()` to drop every managed reference held by
 * the dying object's fields. This slot is conceptually distinct from
 * `finalizer` — see docs/feng-lifetime.md §11/§13.2:
 *
 *   - `finalizer` is OPTIONAL and reflects user-declared semantics only.
 *     The cycle collector invokes it under the §13.2 two-phase rule and
 *     re-checks refcount afterwards (resurrection support).
 *   - `release_children` is unconditionally generated by codegen for every
 *     type that holds at least one managed field. The cycle collector NEVER
 *     calls it on objects in a reclaimed cycle (the collector frees the
 *     whole component as a unit, so per-field releases would dec refcounts
 *     of objects that are about to be freed alongside).
 *
 * Built-in tags (string/array) leave this slot NULL and rely on the
 * tag-specific runtime hook (`feng_string_finalize_internal` etc.). */
typedef void (*FengReleaseChildrenFn)(void *self);

/* Static description of a single managed reference slot inside an object.
 * `offset` is the byte offset of the slot relative to the object base
 * (i.e. relative to its FengManagedHeader). `static_desc` is the descriptor
 * the slot was declared to hold; it MAY be NULL when the slot is polymorphic
 * (e.g. a closure capture of a managed value whose precise type the codegen
 * cannot pin down at emission time). The cycle collector treats `static_desc`
 * as a hint only — the actual descriptor of the pointed-to object is always
 * read from its own header.
 *
 * This metadata is consumed exclusively by the runtime cycle collector
 * (Phase 1B). The deterministic ARC release path does not consult it; the
 * codegen-emitted user finalizer remains the sole owner of the per-field
 * release sequence so the ARC fast path stays Phase 1A compatible. */
typedef struct FengManagedFieldDescriptor {
    size_t offset;
    const struct FengTypeDescriptor *static_desc;
} FengManagedFieldDescriptor;

typedef struct FengTypeDescriptor {
    const char *name;            /* fully-qualified, debug-only */
    size_t size;                 /* total instance bytes incl. header (0 for variable-length) */
    FengFinalizerFn finalizer;   /* optional user-defined finalizer (semantic) */
    FengReleaseChildrenFn release_children; /* codegen-emitted; see typedef */

    /* --- Phase 1B reference-graph metadata ----------------------------- */

    /* True iff the static type-reference graph places this type in a
     * non-trivial strongly-connected component (i.e. self-loop or part of a
     * cycle). The cycle collector only ever enqueues objects whose descriptor
     * has this flag set; acyclic objects bypass the candidate buffer entirely
     * and follow the deterministic ARC release path with zero collector
     * overhead. */
    bool is_potentially_cyclic;

    /* Static trace table: enumeration of every managed reference slot
     * directly held by an instance of this type. Fixed-layout types (user
     * `type`, closures with concrete capture lists) populate it; variable-
     * layout built-ins (string/array) leave it empty and expose their
     * managed children through a tag-specific runtime hook instead. */
    size_t managed_field_count;
    const FengManagedFieldDescriptor *managed_fields;
} FengTypeDescriptor;

/* Built-in descriptors used by string/array helpers. Generated code may also
 * reference them when emitting array-of-string or array-of-array slots. */
extern const FengTypeDescriptor feng_string_descriptor;
extern const FengTypeDescriptor feng_array_descriptor;

/* --- Managed object header --------------------------------------------- */

typedef struct FengManagedHeader {
    const FengTypeDescriptor *desc;
    FengTypeTag tag;
    /* refcount == UINT32_MAX marks the object as immortal (string literals,
     * runtime-internal singletons). retain/release skip such objects. */
    uint32_t refcount;
    /* Phase 1B cycle collector workspace. The field is read-only outside the
     * collector; acyclic objects (descriptor->is_potentially_cyclic == false)
     * never have it mutated from the zero-initialised state, so the ARC fast
     * path remains free of collector overhead.
     *
     * Encoded layout:
     *   bits 0..1 — Bacon-Rajan colour:
     *               0 = BLACK   (in use; default after calloc)
     *               1 = GREY    (currently being traced)
     *               2 = WHITE   (provisionally part of an unreachable cycle)
     *               3 = PURPLE  (reserved for future incremental collector)
     *   bit  2    — buffered: object is currently sitting in the candidate
     *               buffer waiting for a collection cycle.
     *   bit  3    — collecting: object is in the white-set the collector is
     *               currently freeing; feng_release must not run the ARC
     *               finalize path for it (the collector owns its destruction
     *               in Phase 2). */
    uint32_t cycle_state;
} FengManagedHeader;

#define FENG_REFCOUNT_IMMORTAL ((uint32_t)0xFFFFFFFFu)

/* --- retain / release / barriers --------------------------------------- */

void *feng_retain(void *obj);
void  feng_release(void *obj);

/* Slot assignment with RC barrier:
 *   release(*slot); *slot = retain(new_value); */
void  feng_assign(void **slot, void *new_value);

/* Take ownership of a slot, leaving it NULL. Refcount is unchanged: the caller
 * inherits the +1 reference. */
void *feng_take(void **slot);

/* --- Value model: by-value aggregates with managed slots --------------- */
/*
 * The runtime classifies every Feng value into one of three categories
 * (see dev/feng-value-model-delivered.md §2):
 *
 *   FENG_VALUE_TRIVIAL          — bytes only, no retain/release; codegen
 *                                 emits direct C assignment / memcpy.
 *   FENG_VALUE_MANAGED_POINTER  — single managed pointer, handled by the
 *                                 existing single-pointer primitives.
 *   FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS — by-value composite holding
 *                                 at least one managed slot; lifecycle is
 *                                 driven by FengAggregateValueDescriptor
 *                                 below.
 *
 * `FengValueKind` is consumed by codegen for site dispatch and by the
 * runtime array layer for per-element dispatch (see feng_array_new_kinded);
 * the single-pointer primitives themselves never branch on it. */
typedef enum FengValueKind {
    FENG_VALUE_TRIVIAL = 1,
    FENG_VALUE_MANAGED_POINTER = 2,
    FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS = 3
} FengValueKind;

/* Single managed slot inside a by-value aggregate. `offset` is measured from
 * the aggregate value's base address (NOT from a FengManagedHeader). */
typedef enum FengManagedSlotKind {
    /* Slot itself is one managed pointer. The aggregate APIs use
     * feng_retain/feng_release/feng_assign on `*(void**)(value + offset)`. */
    FENG_SLOT_POINTER = 1,
    /* Slot embeds another by-value aggregate; walker recurses through
     * `nested`. */
    FENG_SLOT_NESTED_AGGREGATE = 2
} FengManagedSlotKind;

typedef struct FengManagedSlotDescriptor {
    size_t offset;
    FengManagedSlotKind kind;
    /* Required iff kind == FENG_SLOT_NESTED_AGGREGATE; otherwise must be
     * NULL. */
    const struct FengAggregateValueDescriptor *nested;
} FengManagedSlotDescriptor;

/* Default-initialisation strategy for an aggregate value. Some aggregates
 * (e.g. fat object-form spec) cannot tolerate all-zero bytes as their
 * default state because their managed slots must point at retained, valid
 * objects from the very first observation. */
typedef enum FengAggregateDefaultKind {
    /* All-zero bytes (NULL pointers in every managed slot) is a legal
     * default. feng_aggregate_default_init resolves to memset(0). */
    FENG_DEFAULT_ZERO_BYTES = 1,
    /* Type provides a custom initialiser that produces a fully-constructed
     * value with all managed slots properly retained. */
    FENG_DEFAULT_INIT_FN = 2
} FengAggregateDefaultKind;

/* Init function contract: on entry `value_out` points to `desc->size` bytes
 * of indeterminate content; on return, every managed slot must hold either
 * NULL or a +1 retained reference, and any non-managed bytes must hold a
 * legal value. The function MUST NOT throw a Feng exception. */
typedef void (*FengAggregateDefaultInitFn)(void *value_out);

typedef struct FengAggregateDefaultInitDescriptor {
    FengAggregateDefaultKind kind;
    /* Only consulted when kind == FENG_DEFAULT_INIT_FN. */
    FengAggregateDefaultInitFn init_fn;
} FengAggregateDefaultInitDescriptor;

typedef struct FengAggregateValueDescriptor {
    /* Fully-qualified, debug-only. May be NULL. */
    const char *name;
    /* Total bytes the aggregate occupies. */
    size_t size;
    /* Default-initialisation policy. MUST be non-NULL; the runtime panics
     * on default-init of a NULL policy. */
    const FengAggregateDefaultInitDescriptor *default_init;
    /* Managed slot table in declaration order. Slots that are non-managed
     * (trivial bytes) are NOT enumerated. */
    size_t managed_slot_count;
    const FengManagedSlotDescriptor *managed_slots;
} FengAggregateValueDescriptor;

/* Five canonical operations over by-value aggregates. All are NULL-safe
 * with respect to managed slot pointers (NULL pointers are skipped); they
 * panic on a NULL `desc` or NULL `value`/`dst`/`src` (programmer error). */

/* Retain every managed pointer reachable from `value` according to `desc`. */
void feng_aggregate_retain(void *value,
                           const FengAggregateValueDescriptor *desc);

/* Release every managed pointer reachable from `value` according to `desc`.
 * After return, the managed slot bytes are unchanged but the references
 * they once held have been dropped; the caller MUST NOT observe those
 * pointers again (typically the value's storage is about to be overwritten
 * or its stack frame popped). */
void feng_aggregate_release(void *value,
                            const FengAggregateValueDescriptor *desc);

/* Assignment: semantically equivalent to `*dst = *src` while keeping the
 * refcount invariants of every managed slot.
 *
 * Self-assignment (`dst == src`) is a no-op. The implementation retains
 * every source slot first, releases every destination slot next, then
 * memcpys the whole aggregate; this gives correct results when source and
 * destination share managed children. */
void feng_aggregate_assign(void *dst, const void *src,
                           const FengAggregateValueDescriptor *desc);

/* Move: transfers ownership of every managed slot from `src` to `dst`.
 * After return, every managed slot in `src` is set to NULL; non-managed
 * bytes in `src` are left as-is. The destination's previous managed slots
 * are released as in feng_aggregate_release.
 *
 * Self-move (`dst == src`) is a no-op. */
void feng_aggregate_take(void *dst, void *src,
                         const FengAggregateValueDescriptor *desc);

/* Initialise `value_out` to the descriptor's default value. */
void feng_aggregate_default_init(void *value_out,
                                 const FengAggregateValueDescriptor *desc);

/* --- String ------------------------------------------------------------ */

typedef struct FengString FengString;

/* Allocates a fresh immortal string holding a copy of the supplied UTF-8 bytes.
 * Codegen caches the returned pointer per literal site so each literal allocates
 * exactly once at first use. The buffer is null-terminated. */
FengString *feng_string_literal(const char *utf8, size_t length);

/* Process-wide singleton empty string used as the `string` default zero value.
 * Stamped IMMORTAL so retain/release are no-ops; safe to share across threads.
 * Generated code uses this at every binding/field site that has no explicit
 * initialiser so `string` defaults to a real empty string rather than NULL. */
FengString *feng_string_default(void);

/* Concatenation always returns a fresh +1 string; either operand may be NULL,
 * which is treated as the empty string. */
FengString *feng_string_concat(const FengString *left, const FengString *right);

size_t      feng_string_length(const FengString *s);
const char *feng_string_data(const FengString *s);

/* --- Array ------------------------------------------------------------- */

typedef struct FengArray FengArray;

/* Creates a fresh +1 array. Element classification follows
 * dev/feng-value-model-delivered.md §7.3:
 *
 *   FENG_VALUE_TRIVIAL          — `element_aggregate` MUST be NULL; slots
 *                                 hold raw bytes and finalize merely frees
 *                                 the storage.
 *   FENG_VALUE_MANAGED_POINTER  — `element_aggregate` MUST be NULL;
 *                                 element_size MUST equal sizeof(void *);
 *                                 each non-NULL slot is feng_release'd on
 *                                 finalize.
 *   FENG_VALUE_AGGREGATE_WITH_MANAGED_SLOTS — `element_aggregate` MUST be
 *                                 non-NULL and `element_size` MUST equal
 *                                 `element_aggregate->size`; each element is
 *                                 released via feng_aggregate_release on
 *                                 finalize.
 *
 * `element_desc` is currently used only for diagnostics; pass NULL when the
 * caller has nothing meaningful (e.g. aggregate elements). All
 * preconditions are enforced with feng_panic to surface descriptor /
 * codegen mistakes early. */
FengArray *feng_array_new_kinded(FengValueKind element_kind,
                                 const FengAggregateValueDescriptor *element_aggregate,
                                 const FengTypeDescriptor *element_desc,
                                 size_t element_size,
                                 size_t length);

/* Legacy two-way constructor preserved verbatim for callers that have not
 * yet adopted the kinded API. Wraps feng_array_new_kinded with
 * `element_aggregate = NULL` and dispatches `element_is_managed` to
 * MANAGED_POINTER vs TRIVIAL. New code MUST use feng_array_new_kinded for
 * aggregate-element arrays. */
FengArray *feng_array_new(const FengTypeDescriptor *element_desc,
                          size_t element_size,
                          bool element_is_managed,
                          size_t length);

size_t feng_array_length(const FengArray *array);
void  *feng_array_data(FengArray *array);
void   feng_array_check_index(const FengArray *array, size_t index);

/* Reports the per-element classification recorded at array creation. The
 * runtime itself does not branch on this value (the finalize path uses
 * the cached classification directly); callers that walk arrays from
 * generated code may consult it to pick the correct copy/assign path. */
FengValueKind feng_array_element_kind(const FengArray *array);

/* Returns the per-element aggregate descriptor for AGGREGATE-kind arrays,
 * or NULL otherwise. */
const FengAggregateValueDescriptor *feng_array_element_aggregate(const FengArray *array);

/* --- Object ------------------------------------------------------------ */

/* Allocates a zero-initialised instance whose first member is FengManagedHeader.
 * desc->size MUST cover the full struct including the header. */
void *feng_object_new(const FengTypeDescriptor *desc);

/* --- Exceptions -------------------------------------------------------- */

/* Linked-list node living on the C stack. Generated code pushes one of these
 * at every managed local's declaration site (binding or materialised
 * temporary) and pops it on the corresponding scope exit. On throw, the
 * runtime walks the chain back to the catching frame's snapshot and releases
 * every non-NULL `*slot`, then nulls the slot to avoid double-free. This is
 * how Phase 1A guarantees "exception path cleanup" without hoisting locals
 * to the function prologue. */
typedef struct FengCleanupNode {
    struct FengCleanupNode *prev;
    void                  **slot;
} FengCleanupNode;

typedef struct FengExceptionFrame {
    struct FengExceptionFrame *prev;
    jmp_buf jb;
    void   *value;
    int     is_managed;
    /* Snapshot of the cleanup chain top at the moment this frame was pushed.
     * On throw, the runtime walks down to (but not past) this node. */
    struct FengCleanupNode *cleanup_top;
} FengExceptionFrame;

void feng_exception_push(FengExceptionFrame *frame);
void feng_exception_pop(void);

/* Push/pop a managed local onto the cleanup chain. `node` must outlive the
 * scope of `slot` and is typically a stack-allocated FengCleanupNode adjacent
 * to the local. Pop must be called in strict LIFO order. */
void feng_cleanup_push(FengCleanupNode *node, void **slot);
void feng_cleanup_pop(void);

#if defined(__GNUC__) || defined(__clang__)
void feng_exception_throw(void *value, int is_managed) __attribute__((noreturn));
#else
void feng_exception_throw(void *value, int is_managed);
#endif

FengExceptionFrame *feng_exception_current(void);

/* --- Panic ------------------------------------------------------------- */

#if defined(__GNUC__) || defined(__clang__)
void feng_panic(const char *fmt, ...) __attribute__((noreturn, format(printf, 1, 2)));
#else
void feng_panic(const char *fmt, ...);
#endif

/* --- Lifecycle --------------------------------------------------------- */

/* Drains any potentially-cyclic objects still sitting in the cycle
 * collector's candidate buffer and releases collector-owned heap. Codegen
 * emits a call to this from main() immediately before returning, so user
 * cycles formed but never reclaimed during normal execution still reach
 * their finalizers at process exit. Idempotent and thread-safe. */
void feng_runtime_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif /* FENG_RUNTIME_H */
