#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "parser/parser.h"
#include "semantic/semantic.h"
#include "symbol/export.h"
#include "symbol/ft.h"
#include "symbol/ft_internal.h"
#include "symbol/imported_module.h"

#define CHECK(condition) do { \
    if (!(condition)) { \
        fprintf(stderr, "%s:%d: G24 failed: %s\n", __FILE__, __LINE__, #condition); \
        exit(1); \
    } \
} while (0)

/* Parse and analyze one independent source, optionally against real FT data. */
static FengSemanticAnalysis *g24_analyze(const char *source,
                                        const FengSemanticImportedModuleQuery *query,
                                        FengProgram **program) {
    FengParseError parse_error = {0};
    FengSemanticError *errors = NULL;
    size_t count = 0U;
    FengSemanticAnalysis *analysis = NULL;
    FengSemanticAnalyzeOptions options = {0};
    bool parsed = feng_parse_source(source, strlen(source), "g24_projection.ff", program, &parse_error);
    if (!parsed) fprintf(stderr, "%s\n%s\n", source, parse_error.message);
    CHECK(parsed);
    const FengProgram *programs[] = {*program};
    options.target = FENG_COMPILE_TARGET_LIB;
    options.pointer_size = feng_get_host_pointer_size();
    options.imported_modules = query;
    bool valid = feng_semantic_analyze_with_options(programs, 1U, &options, &analysis, &errors, &count);
    if (!valid) {
        fprintf(stderr, "%s\n", source);
        for (size_t index = 0U; index < count; ++index)
            fprintf(stderr, "%s %s\n", errors[index].code, errors[index].message);
    }
    CHECK(valid && count == 0U);
    feng_semantic_errors_free(errors, count);
    return analysis;
}

/* Read generated bytes independently of the FT reader under test. */
static unsigned char *g24_read_bytes(const char *path, size_t *length) {
    FILE *file = fopen(path, "rb");
    CHECK(file != NULL && fseek(file, 0L, SEEK_END) == 0);
    long end = ftell(file);
    CHECK(end >= 64L && fseek(file, 0L, SEEK_SET) == 0);
    *length = (size_t)end;
    unsigned char *bytes = malloc(*length);
    CHECK(bytes != NULL && fread(bytes, 1U, *length, file) == *length);
    CHECK(fclose(file) == 0);
    return bytes;
}

/* Read/write little-endian wire integers without native struct casts. */
static uint64_t g24_read_le(const unsigned char *bytes, size_t width) {
    uint64_t value = 0U;
    for (size_t index = 0U; index < width; ++index) value |= (uint64_t)bytes[index] << (index * 8U);
    return value;
}

/* Mutate one wire field; callers recompute the payload fingerprint separately. */
static void g24_write_le(unsigned char *bytes, size_t width, uint64_t value) {
    for (size_t index = 0U; index < width; ++index) bytes[index] = (unsigned char)(value >> (index * 8U));
}

/* Find one section from the actual directory instead of hard-coding offsets. */
static size_t g24_section(const unsigned char *bytes, uint16_t kind) {
    size_t directory = (size_t)g24_read_le(bytes + 0x18, 8U);
    size_t count = (size_t)g24_read_le(bytes + 0x0C, 2U);
    for (size_t index = 0U; index < count; ++index) {
        size_t offset = directory + index * 32U;
        if (g24_read_le(bytes + offset, 2U) == kind) return offset;
    }
    return SIZE_MAX;
}

/* Retain a valid checksum so malformed metadata reaches structural validation. */
static void g24_rehash(unsigned char *bytes, size_t length) {
    size_t payload = (size_t)g24_read_le(bytes + 0x20, 8U);
    uint64_t hash = UINT64_C(14695981039346656037);
    CHECK(payload <= length);
    for (size_t index = payload; index < length; ++index) {
        hash ^= bytes[index];
        hash *= UINT64_C(1099511628211);
    }
    g24_write_le(bytes + 0x28, 8U, hash);
}

/* Every independent malformed table must fail reading, not later codegen. */
static void g24_expect_bad(unsigned char *bytes, size_t length, const char *message) {
    FengSymbolGraph *graph = NULL;
    FengSymbolError error = {0};
    g24_rehash(bytes, length);
    CHECK(!feng_symbol_ft_read_bytes(bytes, length, "g24_bad.ft", NULL, &graph, &error));
    if (error.message == NULL || strstr(error.message, message) == NULL)
        fprintf(stderr, "expected '%s', got '%s'\n", message, error.message != NULL ? error.message : "none");
    CHECK(error.message != NULL && strstr(error.message, message) != NULL);
    CHECK(graph == NULL);
    feng_symbol_error_free(&error);
}

/* A graph clone and reader clone must preserve both ownership and open slots. */
static void g24_check_graph(const FengSymbolGraph *graph) {
    const FengSymbolModuleGraph *module = feng_symbol_graph_module_at(graph, 0U);
    const FengSymbolDeclView *scan = NULL;
    CHECK(module != NULL);
    for (size_t index = 0U; index < module->root_decl.member_count; ++index) {
        const FengSymbolDeclView *decl = module->root_decl.members[index];
        if (strcmp(decl->name, "scan") == 0) scan = decl;
    }
    if (scan == NULL || scan->reifiable_union_projection_count != 3U) {
        fprintf(stderr, "G24 graph scan=%p projections=%zu modules=%zu\n", (const void *)scan,
            scan != NULL ? scan->reifiable_union_projection_count : 0U, feng_symbol_graph_module_count(graph));
        for (size_t index = 0U; index < module->root_decl.member_count; ++index)
            fprintf(stderr, "  %s projections=%zu\n", module->root_decl.members[index]->name,
                    module->root_decl.members[index]->reifiable_union_projection_count);
    }
    CHECK(scan != NULL && scan->reifiable_union_projection_count == 3U);
    const char *subjects[] = {"Z", "A", "A"};
    const char *paths[] = {"i32", "i32", "string"};
    for (size_t slot = 0U; slot < 3U; ++slot) {
        const FengSymbolUnionProjectionView *projection = &scan->reifiable_union_projections[slot];
        CHECK(projection->subject_type->kind == FENG_SYMBOL_TYPE_KIND_TYPE_PARAM_REF);
        CHECK(strcmp(projection->subject_type->as.type_param_ref.name, subjects[slot]) == 0);
        CHECK(projection->subject_type->target_decl != NULL);
        CHECK(projection->subject_type->target_decl->owner == scan);
        CHECK(projection->path_count == 1U && projection->result_type == NULL);
        CHECK(projection->path[0]->kind == FENG_SYMBOL_TYPE_KIND_BUILTIN);
        CHECK(strcmp(projection->path[0]->as.builtin.name, paths[slot]) == 0);
        CHECK(projection->constraint_type->kind == FENG_SYMBOL_TYPE_KIND_NAMED);
        CHECK(projection->constraint_type->as.named.segment_count == 3U);
    }
}

/* FT 2.0 records must reject version/shape/owner/path/slot/count corruption.
 * Each mutation starts from the same known-good real writer output. */
static void g24_corruption_matrix(const unsigned char *original, size_t length) {
    size_t section = g24_section(original, FENG_SYMBOL_FT_SEC_UNION_PROJECTIONS);
    size_t records = (size_t)g24_read_le(original + section + 0x08, 8U);
    size_t tseq_section = g24_section(original, FENG_SYMBOL_FT_SEC_TSEQ);
    size_t tseq = (size_t)g24_read_le(original + tseq_section + 0x08, 8U);
    size_t path = tseq + (size_t)g24_read_le(original + records + 0x10, 4U) * 12U;
    size_t attrs_section = g24_section(original, FENG_SYMBOL_FT_SEC_ATTRS);
    size_t attrs = (size_t)g24_read_le(original + attrs_section + 0x08, 8U);
    size_t attr_count = (size_t)g24_read_le(original + attrs_section + 0x04, 4U);
    size_t count_attr = SIZE_MAX;
    for (size_t index = 0U; index < attr_count; ++index)
        if (g24_read_le(original + attrs + index * 20U + 4U, 2U) == 13U) count_attr = attrs + index * 20U;
    CHECK(section != SIZE_MAX && count_attr != SIZE_MAX);
    unsigned char *bytes = malloc(length);
    CHECK(bytes != NULL);
    for (size_t variant = 0U; variant < 22U; ++variant) {
        memcpy(bytes, original, length);
        const char *message = "union projection";
        switch (variant) {
            case 0U: bytes[5] = 1U; message = "unsupported .ft header shape"; break;
            case 1U: bytes[5] = 3U; message = "unsupported .ft header shape"; break;
            case 2U: g24_write_le(bytes + section, 2U, 0xFFU); message = "missing required"; break;
            case 3U: g24_write_le(bytes + section + 2U, 2U, 0U); break;
            case 4U: g24_write_le(bytes + section + 0x18, 4U, 28U); break;
            case 5U: g24_write_le(bytes + section + 0x10, 8U, 1U); break;
            case 6U: g24_write_le(bytes + records, 4U, 0U); break;
            case 7U: g24_write_le(bytes + records + 4U, 4U, 1U); break;
            case 8U: g24_write_le(bytes + records + 32U + 4U, 4U, 0U); break;
            case 9U: g24_write_le(bytes + records + 8U, 4U, 0U); break;
            case 10U: g24_write_le(bytes + records + 12U, 4U, 0U); break;
            case 11U: g24_write_le(bytes + records + 16U, 4U, UINT32_MAX); break;
            case 12U: g24_write_le(bytes + records + 20U, 4U, 0U); break;
            case 13U: g24_write_le(bytes + records + 20U, 4U, UINT32_MAX); break;
            case 14U: g24_write_le(bytes + records + 28U, 4U, 2U); break;
            case 15U: g24_write_le(bytes + records + 28U, 4U, 1U); break;
            case 16U: g24_write_le(bytes + path + 4U, 4U, 0U); break;
            case 17U: g24_write_le(bytes + path, 4U, 1U); break;
            case 18U: g24_write_le(bytes + path + 8U, 4U, 1U); break;
            case 19U: g24_write_le(bytes + count_attr + 8U, 4U, 0U); break;
            case 20U: g24_write_le(bytes + count_attr + 8U, 4U, 4U); break;
            case 21U: g24_write_le(bytes + count_attr + 4U, 2U, 0xFFU); break;
        }
        g24_expect_bad(bytes, length, message);
    }
    free(bytes);
}

/* Source order and generic parameter spelling order cannot allocate slots.
 * Verify both profiles, then destroy the producer before real FT restoration. */
static void g24_slot_roundtrip(const char *directory) {
    const char *bodies[] = {
        "if a match string {} if z match i32 {} if a match i32 {} if z match i32 {}",
        "if z match i32 {} if a match i32 {} if a match string {} if z match i32 {}"
    };
    unsigned char *first = NULL;
    size_t first_length = 0U;
    for (size_t order = 0U; order < 2U; ++order) {
        char source[1024], file[512];
        snprintf(source, sizeof(source), "open module g24.projection; open spec Choice: i32 | string;\n"
            "open func scan<Z: Choice, A: Choice>(z: Z, a: A) { %s }\n", bodies[order]);
        FengProgram *program = NULL;
        FengSemanticAnalysis *analysis = g24_analyze(source, NULL, &program);
        FengSymbolGraph *graph = NULL;
        FengSymbolError error = {0};
        CHECK(feng_symbol_build_graph(analysis, &graph, &error));
        g24_check_graph(graph);
        for (size_t profile = 1U; profile <= 2U; ++profile) {
            snprintf(file, sizeof(file), "%s/projection.ft", directory);
            CHECK(feng_symbol_ft_write_module(feng_symbol_graph_module_at(graph, 0U),
                (FengSymbolProfile)profile, file, &error));
            size_t length;
            unsigned char *bytes = g24_read_bytes(file, &length);
            CHECK(bytes[5] == 2U && bytes[6] == 0U);
            FengSymbolGraph *loaded = NULL;
            CHECK(feng_symbol_ft_read_bytes(bytes, length, file, NULL, &loaded, &error));
            g24_check_graph(loaded);
            feng_symbol_graph_free(loaded);
            if (profile == 1U) {
                g24_corruption_matrix(bytes, length);
                if (first == NULL) {
                    first = malloc(length);
                    CHECK(first != NULL);
                    memcpy(first, bytes, length);
                    first_length = length;
                } else {
                    CHECK(length == first_length && memcmp(first, bytes, length) == 0);
                }
            }
            free(bytes);
        }
        char root[512];
        snprintf(root, sizeof(root), "%s/mod", directory);
        FengSymbolExportOptions options = {0};
        options.public_root = root;
        CHECK(feng_symbol_export_analysis(analysis, &options, &error));
        feng_symbol_graph_free(graph);
        feng_semantic_analysis_free(analysis);
        feng_program_free(program);
        FengSymbolProvider *provider = NULL;
        CHECK(feng_symbol_provider_create(&provider, &error));
        CHECK(feng_symbol_provider_add_ft_root(provider, root, FENG_SYMBOL_PROFILE_PACKAGE_PUBLIC, &error));
        FengSymbolImportedModuleCache *cache = feng_symbol_imported_module_cache_create(provider);
        CHECK(cache != NULL);
        FengSemanticImportedModuleQuery query = feng_symbol_imported_module_cache_as_query(cache);
        analysis = g24_analyze("module consumer; import g24.projection;\n"
            "func use() { scan<i32, string>(1, \"two\"); }\n", &query, &program);
        CHECK(feng_symbol_imported_module_cache_populate_codegen_metadata(cache, analysis));
        const FengReifiableDepSet *set = NULL;
        for (size_t index = 0U; index < analysis->reifiable_dep_set_count; ++index) {
            const FengReifiableDepSet *candidate = &analysis->reifiable_dep_sets[index];
            if (candidate->union_projection_count == 3U) set = candidate;
        }
        CHECK(set != NULL);
        const char *names[] = {"Z", "A", "A"};
        for (size_t slot = 0U; slot < 3U; ++slot) {
            FengSlice name = set->union_projections[slot].subject_type_ref->as.named.segments[0];
            CHECK(name.length == 1U && name.data[0] == names[slot][0]);
            CHECK(feng_semantic_union_projection_slot(set, &set->union_projections[slot]) == slot);
        }
        feng_semantic_analysis_free(analysis);
        feng_program_free(program);
        feng_symbol_imported_module_cache_free(cache);
        feng_symbol_provider_free(provider);
        feng_symbol_error_free(&error);
    }
    free(first);
}

/* Check long paths and independent type/method domains in the loaded graph. */
static void g24_check_owner_paths(const FengSymbolDeclView *decl, size_t depth,
                                  size_t *owner_count, size_t *method_count) {
    if (decl->reifiable_union_projection_count > 0U) {
        CHECK(decl->reifiable_union_projection_count ==
              (decl->kind == FENG_SYMBOL_DECL_KIND_METHOD ? 2U : 1U));
        if (decl->kind == FENG_SYMBOL_DECL_KIND_METHOD) ++*method_count;
        else if (decl->kind == FENG_SYMBOL_DECL_KIND_TYPE) ++*owner_count;
        else CHECK(decl->kind == FENG_SYMBOL_DECL_KIND_FUNCTION);
        for (size_t index = 0U; index < decl->reifiable_union_projection_count; ++index) {
            const FengSymbolUnionProjectionView *projection = &decl->reifiable_union_projections[index];
            CHECK(projection->path_count == depth);
            CHECK(projection->path[depth - 1U]->kind == FENG_SYMBOL_TYPE_KIND_BUILTIN);
            CHECK(strcmp(projection->path[depth - 1U]->as.builtin.name, "i32") == 0);
            for (size_t step = 0U; step + 1U < depth; ++step) {
                char name[32];
                snprintf(name, sizeof(name), "U%zu", depth - step - 1U);
                const FengSymbolTypeView *type = projection->path[step];
                CHECK(type->kind == FENG_SYMBOL_TYPE_KIND_NAMED && type->as.named.segment_count == 3U);
                CHECK(strcmp(type->as.named.segments[2], name) == 0);
            }
            if (decl->kind == FENG_SYMBOL_DECL_KIND_FUNCTION) {
                CHECK(projection->result_type != NULL);
                CHECK(projection->binding_mutability == FENG_MUTABILITY_VAR);
            }
            if (decl->kind == FENG_SYMBOL_DECL_KIND_METHOD) {
                const FengSymbolDeclView *param = projection->subject_type->target_decl;
                CHECK(param != NULL);
                CHECK(param->owner == (index == 0U ? decl->owner : decl));
            }
        }
    }
    for (size_t index = 0U; index < decl->member_count; ++index)
        g24_check_owner_paths(decl->members[index], depth, owner_count, method_count);
}

/* Preserve root-plus-suffix paths beyond eight layers, binding purpose, and
 * separate constructor versus method dependencies in both FT profiles. */
static void g24_owner_path_roundtrips(const char *directory) {
    const size_t depths[] = {1U, 8U, 9U, 17U};
    for (size_t variant = 0U; variant < sizeof(depths) / sizeof(depths[0]); ++variant) {
        size_t depth = depths[variant];
        char source[8192], chain[1024], file[512];
        size_t used = (size_t)snprintf(source, sizeof(source),
            "open module g24.paths; open spec U1: i32 | string;\n");
        for (size_t level = 2U; level <= depth; ++level)
            used += (size_t)snprintf(source + used, sizeof(source) - used,
                "open spec U%zu: U%zu | bool;\n", level, level - 1U);
        size_t chain_used = 0U;
        for (size_t level = depth; level > 1U; --level)
            chain_used += (size_t)snprintf(chain + chain_used, sizeof(chain) - chain_used,
                                          "U%zu -> ", level - 1U);
        snprintf(chain + chain_used, sizeof(chain) - chain_used, "i32");
        used += (size_t)snprintf(source + used, sizeof(source) - used,
            "open func read<T: U%zu>(v: T): i32 { return match v { var x: %s { x } else { -1 } }; }\n"
            "open type Host<Z: U%zu> {\n"
            " open var value: Z;\n"
            " open func Host(v: Z) { self.value = v; if v match %s {} }\n"
            " open func scan<A: U%zu>(a: A) { if a match %s {} if self.value match %s {} }\n"
            "}\n", depth, chain, depth, chain, depth, chain, chain);
        CHECK(used < sizeof(source));
        FengProgram *program = NULL;
        FengSemanticAnalysis *analysis = g24_analyze(source, NULL, &program);
        FengSymbolGraph *graph = NULL;
        FengSymbolError error = {0};
        CHECK(feng_symbol_build_graph(analysis, &graph, &error));
        for (size_t profile = 1U; profile <= 2U; ++profile) {
            snprintf(file, sizeof(file), "%s/paths.ft", directory);
            CHECK(feng_symbol_ft_write_module(feng_symbol_graph_module_at(graph, 0U),
                                               (FengSymbolProfile)profile, file, &error));
            FengSymbolGraph *loaded = NULL;
            CHECK(feng_symbol_ft_read_file(file, NULL, &loaded, &error));
            size_t owners = 0U, methods = 0U;
            g24_check_owner_paths(&feng_symbol_graph_module_at(loaded, 0U)->root_decl,
                                   depth, &owners, &methods);
            CHECK(owners == 1U && methods == 1U);
            feng_symbol_graph_free(loaded);
        }
        char root[512];
        snprintf(root, sizeof(root), "%s/depth-%zu", directory, depth);
        FengSymbolExportOptions export_options = {0};
        export_options.public_root = root;
        CHECK(feng_symbol_export_analysis(analysis, &export_options, &error));
        feng_symbol_graph_free(graph);
        feng_semantic_analysis_free(analysis);
        feng_program_free(program);

        /* ISSUE-G24-017: producer AST is gone. Imported nested members must
         * remain unions before consumer admission, not just during Codegen. */
        FengSymbolProvider *provider = NULL;
        CHECK(feng_symbol_provider_create(&provider, &error));
        CHECK(feng_symbol_provider_add_ft_root(provider, root,
                                               FENG_SYMBOL_PROFILE_PACKAGE_PUBLIC, &error));
        FengSymbolImportedModuleCache *cache = feng_symbol_imported_module_cache_create(provider);
        CHECK(cache != NULL);
        FengSemanticImportedModuleQuery query = feng_symbol_imported_module_cache_as_query(cache);
        char consumer[2048];
        snprintf(consumer, sizeof(consumer),
            "module consumer; import g24.paths;\n"
            "func use(v: i32, w: U%zu): U%zu { read<i32>(v); read<string>(\"leaf\");\n"
            " read<U%zu>(w); let host = Host<i32>(v); host.scan<string>(\"leaf\"); return v; }\n"
            "func rejected_type(value: f64) {}\n", depth, depth, depth);
        analysis = g24_analyze(consumer, &query, &program);
        const FengCallableSignature *use = &program->declarations[0]->as.function_decl;
        const FengCallableSignature *rejected = &program->declarations[1]->as.function_decl;
        size_t *indices = NULL, count = 0U;
        CHECK(feng_semantic_query_union_entry(analysis, program, use->params[0].type,
                                               use->params[1].type, &indices, &count));
        CHECK(count == depth);
        for (size_t step = 0U; step < count; ++step) CHECK(indices[step] == 0U);
        free(indices);
        indices = NULL;
        CHECK(!feng_semantic_query_union_entry(analysis, program, rejected->params[0].type,
                                                use->params[1].type, &indices, &count));
        CHECK(indices == NULL && count == 0U);
        feng_semantic_analysis_free(analysis);
        feng_program_free(program);
        feng_symbol_imported_module_cache_free(cache);
        feng_symbol_provider_free(provider);
        feng_symbol_error_free(&error);
    }
}

/* A no-union module still carries the required empty contract marker, with no
 * per-callable projection records or dependencies added to its symbol graph. */
static void g24_empty_projection_roundtrips(const char *directory) {
    FengProgram *program = NULL;
    FengSemanticAnalysis *analysis = g24_analyze(
        "open module g24.empty; open func identity<T>(value: T): T { return value; }\n", NULL, &program);
    FengSymbolGraph *graph = NULL;
    FengSymbolError error = {0};
    CHECK(feng_symbol_build_graph(analysis, &graph, &error));
    for (size_t profile = 1U; profile <= 2U; ++profile) {
        char file[512];
        snprintf(file, sizeof(file), "%s/empty.ft", directory);
        CHECK(feng_symbol_ft_write_module(feng_symbol_graph_module_at(graph, 0U),
                                           (FengSymbolProfile)profile, file, &error));
        size_t length;
        unsigned char *bytes = g24_read_bytes(file, &length);
        size_t section = g24_section(bytes, FENG_SYMBOL_FT_SEC_UNION_PROJECTIONS);
        CHECK(section != SIZE_MAX);
        CHECK(g24_read_le(bytes + section + 4U, 4U) == 0U);
        CHECK(g24_read_le(bytes + section + 0x10, 8U) == 0U);
        FengSymbolGraph *loaded = NULL;
        CHECK(feng_symbol_ft_read_bytes(bytes, length, file, NULL, &loaded, &error));
        const FengSymbolModuleGraph *module = feng_symbol_graph_module_at(loaded, 0U);
        CHECK(module != NULL && module->root_decl.member_count == 1U);
        CHECK(module->root_decl.members[0]->reifiable_union_projection_count == 0U);
        feng_symbol_graph_free(loaded);
        g24_write_le(bytes + section, 2U, 0xFFU);
        g24_expect_bad(bytes, length, "missing required");
        free(bytes);
    }
    feng_symbol_graph_free(graph);
    feng_symbol_error_free(&error);
    feng_semantic_analysis_free(analysis);
    feng_program_free(program);
}

/* Round-trip ordered members through real package-public FT, destroy the
 * producer, then validate typed/literal/call entrances using only imports. */
static void g24_entry_order_roundtrip(const char *directory) {
    const char *source =
        "open module g24.entryorder;\n"
        "open spec L: i16 | string; open spec R: i16 | bool; open spec Both: L | R;\n"
        "open spec Deep: i8 | string; open spec Left: Deep | bool; open spec Wide: Left | R;\n"
        "open spec DefaultInner: int | string; open spec Default: DefaultInner | f64;\n"
        "open spec A {} open spec B {} open type Item: A, B {} open spec AB: A | B;\n"
        "open func take(value: Both): Both { return value; }\n";
    FengProgram *program = NULL;
    FengSemanticAnalysis *analysis = g24_analyze(source, NULL, &program);
    char root[512];
    CHECK(snprintf(root, sizeof(root), "%s/entry-order", directory) < (int)sizeof(root));
    FengSymbolExportOptions options = {0};
    FengSymbolError error = {0};
    options.public_root = root;
    CHECK(feng_symbol_export_analysis(analysis, &options, &error));
    feng_semantic_analysis_free(analysis);
    feng_program_free(program);

    FengSymbolProvider *provider = NULL;
    CHECK(feng_symbol_provider_create(&provider, &error));
    CHECK(feng_symbol_provider_add_ft_root(provider, root,
        FENG_SYMBOL_PROFILE_PACKAGE_PUBLIC, &error));
    FengSymbolImportedModuleCache *cache = feng_symbol_imported_module_cache_create(provider);
    CHECK(cache != NULL);
    FengSemanticImportedModuleQuery query = feng_symbol_imported_module_cache_as_query(cache);
    const char *consumer =
        "module consumer; import g24.entryorder;\n"
        "func typed(x: i16): Both { return x; }\n"
        "func literal(): Both { return 7; }\n"
        "func breadth(): Wide { return 7; }\n"
        "func defaulted(): Default { return 7; }\n"
        "func object(x: Item): AB { return x; }\n"
        "func argument(): Both { return take(7); }\n";
    analysis = g24_analyze(consumer, &query, &program);
    const size_t expected[][2] = {{0, 0}, {0, 0}, {1, 0}, {0, 0}, {0, 0}, {0, 0}};
    CHECK(analysis->union_coercion_site_count == 6U);
    bool seen[6] = {false};
    for (size_t i = 0U; i < analysis->union_coercion_site_count; ++i) {
        const FengUnionCoercionSite *site = &analysis->union_coercion_sites[i];
        size_t index = site->expr->token.line - 2U;
        CHECK(index < 6U && !seen[index]);
        seen[index] = true;
        CHECK(site->path_length == (index == 4U ? 1U : 2U));
        for (size_t part = 0U; part < site->path_length; ++part)
            CHECK(site->path_indices[part] == expected[index][part]);
        if (index != 0U && index != 4U) CHECK(site->literal_source_type_ref != NULL);
    }
    feng_semantic_analysis_free(analysis);
    feng_program_free(program);
    feng_symbol_imported_module_cache_free(cache);
    feng_symbol_provider_free(provider);
    feng_symbol_error_free(&error);
}

/* Public entry: isolated artifacts are ordinary test data under repo temp/. */
void test_g24_union_projection_ft(void) {
    char directory[] = "temp/g24_projection_XXXXXX";
    CHECK(mkdtemp(directory) != NULL);
    g24_slot_roundtrip(directory);
    g24_owner_path_roundtrips(directory);
    g24_empty_projection_roundtrips(directory);
    g24_entry_order_roundtrip(directory);
    puts("G24 union projection FT matrices passed");
}
